// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadNote() {
  return window['go']['main']['App']['LoadNote']();
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function ToggleAlwaysOnTop() {
  return window['go']['main']['App']['ToggleAlwaysOnTop']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
