// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadNote():Promise<string>;

export function SaveNote(arg1:string):Promise<void>;

export function ToggleAlwaysOnTop():Promise<boolean>;

export function ToggleWindow():Promise<boolean>;
